tap "can1357/tap"

brew "can1357/tap/omp"
brew "eza"
brew "gh"
brew "jenv"
brew "jdtls"
brew "openjdk@21"
brew "openjdk@25"
brew "starship"
brew "uv"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

cask "1password"
cask "ghostty"
cask "rectangle"
cask "visual-studio-code"
